---

- name: Add nodesource GPG key
  shell: curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

- name: Add nodesource apt repository
  apt_repository: repo='deb https://deb.nodesource.com/node_0.10 trusty main' state=present

- name: Install nodejs
  apt: name={{ item }} state=present
  with_items:
    - nodejs
