---

- name: Add ruby ppa
  apt_repository: repo='ppa:brightbox/ruby-ng'

- name: Install ruby2.2.x + some related packages
  apt: name={{ item }} state=present
  with_items:
    - ruby2.2
    - ruby2.2-dev
    - ruby-switch

- name: Install bundler
  # For some reason this does not work, so I'm using shell instead
  # gem: name=bundler state=latest user_install=no
  shell: gem install bundler
